# Generated by Django 3.0 on 2020-01-26 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inputs',
            new_name='Input',
        ),
    ]
