# Generated by Django 3.0 on 2020-01-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0002_auto_20200126_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='angry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='input',
            name='happy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='input',
            name='others',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='input',
            name='sad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='input',
            name='stupefied',
            field=models.IntegerField(default=0),
        ),
    ]
