# Generated by Django 3.0 on 2020-02-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='total_accuracy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
    ]
